{
 "title": "System Monitoring",
 "description": "This Grafana Dashboard helps to monitor OS level Statistics.",
 "time": { "from": "2018-09-06T03:03:27.867Z", "to": "2018-09-06T04:05:19.207Z" },
 "templating": {
  "list": [
   {
    "name": "host",
    "query": "show tag values from  LINUX_FREE with key = \"host\" "
   }
  ]
 },
 "panels": [
  { "title": "Quick Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "System CPU Usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "LINUX_VMSTAT",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "SystemCPU" }
     ]
    }
   ]
  },
  {
   "title": "User CPU Usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "LINUX_VMSTAT",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "UserCPU" }
     ]
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "LINUX_TOP_MEM",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 15, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "LINUX_IOSTAT",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "LINUX_IOSTAT",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  { "title": "Network Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "LINUX_NETSTAT",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "type" ], "type": "tag" },
      { "params": [ "deviceid" ], "type": "tag" }
     ],
     "measurement": "LINUX_NETSTAT",
     "query": "SELECT mean(\"value\") FROM \"LINUX_NETSTAT\" WHERE (\"host\" =~ /^$host$/) AND $timeFilter GROUP BY time($__interval), \"host\", \"type\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "WIN-NETWORK",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "type" ], "type": "tag" }
     ],
     "measurement": "WIN_NETSTAT",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  { "title": "I/O Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "LINUX_IOSTAT",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "type" ], "type": "tag" },
      { "params": [ "deviceid" ], "type": "tag" }
     ],
     "measurement": "LINUX_IOSTAT",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "WIN-IOSTAT",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "type" ], "type": "tag" }
     ],
     "measurement": "WIN_IOSTAT",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  { "title": "Memory & VM Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "LINUX_VMSTAT",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "type" ], "type": "tag" }
     ],
     "measurement": "LINUX_VMSTAT",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "WIN-MEM",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "type" ], "type": "tag" }
     ],
     "measurement": "WIN_MEM",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "LINUX_TOP_MEM",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "process" ], "type": "tag" }
     ],
     "measurement": "LINUX_TOP_MEM",
     "query": "SELECT mean(\"value\") FROM \"LINUX_TOP_MEM\" WHERE $timeFilter GROUP BY time($__interval), \"process\", \"host\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "LINUX_FREE",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "kbytes", "label": "Memory in MB" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "type" ], "type": "tag" }
     ],
     "measurement": "LINUX_FREE",
     "query": "SELECT mean(\"value\") FROM \"LINUX_FREE\" WHERE $timeFilter GROUP BY time($__interval), \"host\", \"type\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  { "title": "CPU Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "LINUX_TOP_CPU",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "process" ], "type": "tag" }
     ],
     "measurement": "LINUX_TOP_CPU",
     "query": "SELECT mean(\"value\") FROM \"LINUX_TOP_CPU\" WHERE $timeFilter GROUP BY time($__interval), \"process\", \"host\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "WIN-CPU",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "type" ], "type": "tag" }
     ],
     "measurement": "WIN_CPU",
     "query": "SELECT \"value\" FROM \"WIN_NETSTAT\" WHERE $timeFilter GROUP BY time($__interval), \"host\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  }
 ]
}